services:
  db:
    image: postgres:16
    container_name: railwiseapi
    environment:
      POSTGRES_USER: rail
      POSTGRES_PASSWORD: rail
      POSTGRES_DB: rail_mvp
    ports:
      - "5433:5432"
    volumes:
      - rail_mvp_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rail -d rail_mvp"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  rail_mvp_pgdata:
